# .air.toml
[build]
cmd = "go build -o ./tmp/main ./cmd/main.go"
bin = "tmp/main"
full_bin = "tmp/main"
include_ext = ["go", "tpl", "html"]
exclude_dir = ["tmp", "vendor"]
exclude_file = []
follow_symlink = true
delay = 1000 # ms
stop_on_error = true

[log]
level = "debug"

[color]
main = "yellow"
watcher = "cyan"
build = "green"
runner = "magenta"